allow_arbitrary_names: false

shapes:

creatures:
        
players:
    
help:
  topic:
    help:
      variant:
        1:
          usage: 
          - "&r&f/&6doppel help &f[&6reload&f|&6info&f|&6coords&f|&6kill&f|&6spawn&f|&6maintain&f]"
          description:
          - "&r&f    Show descriptions of &6/doppel &fsubcommands."
          - ""

    reload:
      variant:
        1:
          usage: 
          - "&r&f/&6doppel reload"
          description: 
          - "&r&f    Reload the Doppelganger configuration."
          - ""

    info:
      header: 
      - "&r&eAlternatives: "
      variant:
        list:
          usage: 
          - "&r&f/&6doppel info list"
          description: 
          - "&r&f    List the names of all shapes, creatures and summonable players."
          - ""
        shape:
          usage: 
          - "&r&f/&6doppel info shape &d&oname"
          description: 
          - "&r&f    Describe the named shape."
          - ""
        creature:
          usage: 
          - "&r&f/&6doppel info creature &d&oname"
          description: 
          - "&r&f    Describe the named creature type."
          - ""
        player:
          usage: 
          - "&r&f/&6doppel info player &d&oname"
          description: 
          - "&r&f    Describe the named summonable player."
          - ""

    coords:
      header:
      - "&r&eAlternatives: "
      footer:
      - "&r&eThe world name defaults to that of the player or command block if omitted."
      variant:
        sphere_here:
          usage:
          - "&r&f/&6doppel coords sphere here &a&oradius &f[&d&oname&f]"
          description:
          - "&r    &fList coordinates of doppelgangers with the specified name in a sphere around the player or command block."
          - ""
          
        sphere:
          usage:
          - "&r&f/&6doppel coords sphere &f[&d&oworld&f] &a&ox y z radius &f[&d&oname&f]"
          description:
          - "&r    &fList coordinates of doppelgangers with the specified name in a sphere."
          - ""
          
        box:
          usage:
          - "&r&f/&6doppel coords box &f[&d&oworld&f] &a&ox1 y1 z1 x2 y2 z2 &f[&d&oname&f]"
          description:
          - "&r    &fList coordinates of doppelgangers with the specified name in a box (x1,y1,z1) - (x2,y2,z2)."
          - ""
    
    kill:
      header:
      - "&r&eAlternatives: "
      footer:
      - "&r&eThe world name defaults to that of the player or command block if omitted."
      variant:
        sphere_here:
          usage:
          - "&r&f/&6doppel kill sphere here &a&oradius &d&oname"
          description:
          - "&r    &fKill all doppelgangers with the specified name in a sphere around the player or command block."
          - ""
          
        sphere:
          usage:
          - "&r&f/&6doppel kill sphere &f[&d&oworld&f] &a&ox y z radius &d&oname"
          description:
          - "&r    &fKill all doppelgangers with the specified name in a sphere."
          - ""
          
        box:
          usage:
          - "&r&f/&6doppel kill box &f[&d&oworld&f] &a&ox1 y1 z1 x2 y2 z2 &d&oname"
          description:
          - "&r    &fKill all doppelgangers with the specified name in a box (x1,y1,z1) - (x2,y2,z2)."
          - ""

    spawn:
      header:
      - "&r&eAlternatives: "
      footer:
      - "&r&eNote:"
      - "&r&e* Anonymous doppelgangers cannot be found or killed by commands."
      - "&r&e* The world name defaults to that of the player or command block if omitted."
      variant:
        here:
          usage:
          - "&r&f/&6doppel spawn here &d&otype &f[&d&oname&f]"
          description:
          - "&r&f    Spawn a doppelganger of the specified type, with optional name at the location of the player or command block issuing the command."
          - ""
        at:
          usage:
          - "&r&f/&6doppel spawn at &f[&d&oworld&f] &a&ox y z &d&otype &f[&d&oname&f]"
          description:
          - "&r&f    Spawn a doppelganger of the specified type, at the specified location, with optional name."
          - ""

    maintain:
      header:
      - "&r&eAlternatives: "
      footer:
      - "&r&eThe world name defaults to that of the player or command block if omitted."
      variant:
        box:
          usage:
          - "&r&f/&6doppel maintain at &f[&d&oworld&f] &a&ox y z &r&6box &f[&d&oworld&f] &a&ox1 y1 z1 x2 y2 z2 &d&otype name"
          description:
          - "&r    &fSpawn a doppelganger with the specified name and type at (x,y,z) in the named world if there are no doppelgangers with that name and type in the box (x1,y1,z1) - (x2,y2,z2). If there is more than one doppelganger with that name in the box, kill all but the oldest one."
          - ""

        sphere:
          usage:
          - "&r&f/&6doppel maintain at &f[&d&oworld&f] &a&ox y z &r&6sphere &f[&d&oworld&f] &a&oxc yc zc radius &d&otype name"
          description:
          - "&r    &fSpawn a doppelganger with the specified name and type at (x,y,z) in the named world if there are no doppelgangers with that name and type in the sphere whose centre is (xc,yc,zc).  If there is more than one doppelganger with that name in the sphere, kill all but the oldest one."
          - ""


