name: Doppelganger
main: io.github.totemo.doppelganger.Doppelganger
version: ${project.version}
description: ${project.description}
author: totemo
website: http://github.com/totemo/Doppelganger
commands:
permissions:

