allow_arbitrary_names: false

shapes:
  diamond_t_ns:
    enabled: true
    head: skull_item
    body:
    - material: diamond_block
      offset: [0, -1, -1]
    - material: diamond_block
      offset: [0, -1, 1]
    - material: diamond_block
      offset: [0, -1, 0]
    - material: diamond_block
      offset: [0, -2, 0]
    summon:
    - weight: 1.0
      spawn: ToughWitherSkeleton

  diamond_t_ew:
    head: skull_item
    body:
    - material: diamond_block
      offset: [-1, -1, 0]
    - material: diamond_block
      offset: [1, -1, 0]
    - material: diamond_block
      offset: [0, -1, 0]
    - material: diamond_block
      offset: [0, -2, 0]
    summon:
    - weight: 1.0
      spawn: ToughWitherSkeleton

  diamond_2pillar:
    head: pumpkin
    body:
    - material: diamond_block
      offset: [0, -1, 0]
    - material: diamond_block
      offset: [0, -2, 0]
    summon:
    - weight: 1.0
      spawn: ToughWitherSkeleton

  wool_2pillar:
    head: skull_item
    body:
    - material: wool
      offset: [0, -1, 0]
    - material: wool
      offset: [0, -2, 0]
    summon:
    - weight: 1.0
      spawn: SpecialVillager

  wool_quadruped_sn:
    head: skull_item
    body:
    - material: wool
      offset: [0, 0, -1]
    - material: wool
      offset: [0, 0, -2]
    - material: fence_gate
      offset: [0, -1, -1]
    - material: fence_gate
      offset: [0, -1, -2]
    summon:
    - weight: 1.0
      spawn: SpecialCow

  wool_quadruped_ns:
    head: skull_item
    body:
    - material: wool
      offset: [0, 0, 1]
    - material: wool
      offset: [0, 0, 2]
    - material: fence_gate
      offset: [0, -1, 1]
    - material: fence_gate
      offset: [0, -1, 2]
    summon:
    - weight: 1.0
      spawn: SpecialCow

  wool_quadruped_ew:
    head: skull_item
    body:
    - material: wool
      offset: [-1, 0, 0]
    - material: wool
      offset: [-2, 0, 0]
    - material: fence_gate
      offset: [-1, -1, 0]
    - material: fence_gate
      offset: [-2, -1, 0]
    summon:
    - weight: 1.0
      spawn: SpecialCow

  wool_quadruped_we:
    head: skull_item
    body:
    - material: wool
      offset: [1, 0, 0]
    - material: wool
      offset: [2, 0, 0]
    - material: fence_gate
      offset: [1, -1, 0]
    - material: fence_gate
      offset: [2, -1, 0]
    summon:
    - weight: 1.0
      spawn: SpecialCow

  gold_diamond_2pillar:
    head: pumpkin
    body:
    - material: gold_block
      offset: [0, -1, 0]
    - material: diamond_block
      offset: [0, -2, 0]
    summon:
    - weight: 1.0
      spawn: ToughPigZombie

  pumpkin:
    head: pumpkin
    summon:
    - weight: 1.0
      spawn: SpecialBat
    - weight: 1.0
      spawn: FlyingPig
    - weight: 1.0
      spawn: FlyingSquid


creatures:
  SpecialBat:
    spawn: Bat
    sound: ambience_cave

  SpecialCow:
    spawn: Cow
    sound: ambience_cave
    lightning:
      min: 1
    despawns: false

  SpecialVillager:
    spawn: Villager
    sound: ambience_cave
    lightning:
      min: 1
    despawns: false
    invulnerableticks: 1200
    chestplate:
      item: leather_chestplate
      rgb: [255,0,0]

  RedSkeleton:
    spawn: Skeleton
    lightning:
      min: 1
    despawns: false
    helmet:
      item: leather_helmet
      rgb: [255,0,0]
    chestplate:
      item: leather_chestplate
      rgb: [255,0,0]
    leggings:
      item: leather_leggings
      rgb: [255,0,0]
    boots:
      item: leather_boots
      rgb: [255,0,0]
  
  BlueSkeleton:
    spawn: Skeleton
    lightning:
      min: 1
    despawns: false
    helmet:
      item: leather_helmet
      rgb: [0,0,255]
    chestplate:
      item: leather_chestplate
      rgb: [0,0,255]
    leggings:
      item: leather_leggings
      rgb: [0,0,255]
    boots:
      item: leather_boots
      rgb: [0,0,255]

  ToughWitherSkeleton:
    spawn: WitherSkeleton
    sound: wither_spawn
    lightning:
      min: 1
    despawns: false
    health: 100
    air: 72000
    potions:
    - type: fire_resistance
    - type: damage_resistance
    - type: speed
    - type: regeneration
    - type: increase_damage
      amplifier: 2
    helmet:
      item: skull_item
      damage: 1
      name: The head of a foul beast.
      lore:
      - "This creature was summoned by magic from the darkest depths."
      - "The holder of this grotesque trophy is destined for greatness."
      dropchance: 1.0
    chestplate:
      item: diamond_chestplate
      dropchance: 0.0
    leggings:
      item: diamond_leggings
      dropchance: 0.0
    weapon:
      item: diamond_sword
      name: Witherwell
      lore:
      - "The abysmal blade."
      dropchance: 1.0

  ToughSkeleton:
    spawn: Skeleton
    sound: wither_spawn
    lightning:
      min: 1
    despawns: false
    health: 100
    air: 72000
    potions:
    - type: fire_resistance
    - type: damage_resistance
    - type: speed
    - type: regeneration
    - type: increase_damage
      amplifier: 2
    chestplate:
      item: diamond_chestplate
      damage: 3
      dropchance: 0.0
    weapon:
      item: diamond_sword

  ToughPigZombie:
    spawn: PigZombie
    sound: wither_spawn
    lightning:
      min: 1
    despawns: false
    health: 100
    air: 72000
    potions:
    - type: fire_resistance
    - type: damage_resistance
    - type: speed
    - type: regeneration
    - type: increase_damage
      amplifier: 2
    helmet:
      item: skull_item
      dropchance: 1.0
    weapon:
      item: diamond_sword

  MolonMan:
    defaultname: Minion
    keephelmet: true
    spawn: Skeleton
    sound: ambience_cave
    helmet:
      item: melon_block
    weapon:
      item: stone_sword
      dropchance: 0.01

  MolonMan2:
    defaultname: Henchman
    keephelmet: true
    spawn: Skeleton
    sound: ambience_cave
    helmet:
      item: melon_block
    chestplate:
      item: iron_chestplate
    weapon:
      item: iron_sword
      dropchance: 0.01

  InvisibleBat:
    spawn: Bat
    potions:
    - type: invisibility
      ambient: false

  FlyingPig:
    spawn: Pig
    mount: InvisibleBat
    sound: pig_death

  FlyingSquid:
    spawn: Squid
    mount: InvisibleBat
    sound: swim
    air: 72000
        
  FlyingSaddledPig:
    spawn: SaddledPig
    mount: InvisibleBat

  FlyingWitch:
    spawn: Witch
    mount: InvisibleBat

  WitchOnCaveSpider:
    spawn: Witch
    mount: CaveSpider

  ToughWitherSkeletonOnSpider:
    spawn: ToughWitherSkeleton
    mount: Spider

  InvisibleBlaze:
    spawn: Blaze
    potions:
    - type: invisibility
      ambient: false
    
  FlyingSkull:
    spawn: Skeleton
    despawns: false
    health: 40
    mount: InvisibleBlaze
    potions:
    - type: invisibility
    - type: fire_resistance
    helmet: 
      item: skull_item
      dropchance: 0.0
    weapon:
      item: bow
      enchantments:
      - type: arrow_damage
        level: 5
      - type: arrow_fire
        level: 1

  Notch:
    defaultname: Notch
    health: 80
    air: 72000
    spawn: ToughWitherSkeleton
    despawns: false
    lightning:
      min: 4
      max: 7
    sound: wither_spawn
    helmet:
      item: skull_item
      lore:
      - "From this small container sprung an entire universe."
      dropchance: 1.0001
    chestplate:
      item: diamond_chestplate
      damage: 3
      dropchance: 0.01
      enchantments:
      - type: protection_environmental
        level: 4
    leggings: 
      item: diamond_leggings
      damage: 3
      dropchance: 0.0
      enchantments:
      - type: protection_environmental
        level: 4
    weapon:
      item: diamond_sword
      name: Whittlebone
      lore:
      - "&fThe mighty sword of the great &eNotch."
      - "&9Wield it well."
      damage: 50
      dropchance: 1.0001
      enchantments:
      - type: damage_all
        level: 5
      - type: fire_aspect
        level: 2
    boots:
#      item: tripwire_hook
#      name: The Key of Notch
#      lore:
#      - "The path ahead is now clear."
      item: written_book
      title: "&6The Book of Notch"
      author: "&cNotch"
      lore:
      - "&4&oDo you dare to read it?"
      pages:
      - "&4Rhubarb.\nRhubarb.\nRhubarb.\nRhubarb.\nRhubarb.\n\n..."
      - "&6Custard."
      dropchance: 1.0001
    escorts:
      min: 3
      max: 8
      minrange: 1.0
      maxrange: 5.0
      summon:
      - weight: 1.0
        spawn: FlyingSkull

  jeb_:
    defaultname: jeb_
    health: 60
    air: 72000
    spawn: ToughWitherSkeleton
    despawns: false
    mount: FlyingSaddledPig
    lightning:
      min: 4
      max: 7
      minrange: 1.0
      maxrange: 5.0
      duration: 30
    helmet:
      item: skull_item
      dropchance: 1.0
    chestplate:
      item: diamond_chestplate
      damage: 3
      dropchance: 0.0
      enchantments:
      - type: protection_environmental
        level: 4
    boots:
      item: written_book
      lore:
      - "&4&oA mysterious tome of great power."
      name: "&1The Book of jeb_"
      author: "&2jeb_"
      pages:
      - "&6Beware oh reader, this is not a tale taken lightly.\n\n&cThis book holds great power for good or for evil."
      - "&4And stuff like that.\n\n\n&5THE END."
      dropchance: 1.0001
    weapon:
      item: diamond_sword
      dropchance: 0.05
    escorts:
      min: 8
      max: 12
      minrange: 1.0
      maxrange: 5.0
      summon:
      - weight: 1.0
        spawn: FlyingPig
      - weight: 1.0
        spawn: FlyingWitch
      - weight: 1.0
        spawn: WitchOnCaveSpider
      - weight: 1.0
        spawn: ToughWitherSkeletonOnSpider

  Dinnerbone:
    defaultname: Dinnerbone
    health: 80
    spawn: ToughSkeleton
    despawns: false
    lightning:
      min: 4
      max: 7
      minrange: 1.0
      maxrange: 5.0
      duration: 30
    helmet:
      item: skull_item
      dropchance: 1.0
    weapon:
      dropchance: 0.05
      item: diamond_sword
      enchantments:
      - type: knockback
        level: 2
      - type: fire_aspect
        level: 2
      - type: damage_all
        level: 5
    escorts:
      min: 3
      max: 8
      minrange: 1.0
      maxrange: 5.0
      summon:
      - weight: 1.0
        spawn: ToughSkeleton

  Villain:
    defaultname: Villain
    health: 100
    spawn: ToughWitherSkeleton
    despawns: false
    mask: Ooer
    lightning:
      min: 4
      max: 12
      minrange: 2.0
      maxrange: 10.0
      duration: 100
    helmet:
      item: skull_item
      dropchance: 0.5
    boots:
      item: map
      name: Yarwig's Map
      lore:
      - "Wihout this, you will surely die."
      damage: 0
      dropchance: 1.0001
    weapon:
      dropchance: 0.05
      item: diamond_sword
      enchantments:
      - type: knockback
        level: 2
      - type: fire_aspect
        level: 2
      - type: damage_all
        level: 5
    escorts:
      min: 7
      max: 12
      minrange: 2.0
      maxrange: 20.0
      duration: 100
      summon:
      - weight: 1.0
        spawn: MolonMan
      - weight: 0.5
        spawn: MolonMan2
      - weight: 0.5
        spawn: Bat

        
players:
  Notch:
    spawn: Notch
    shapes:
    - diamond_t_ns
    - diamond_t_ew
        
  jeb_:
    shapes:
    - diamond_t_ns
    - diamond_t_ew

  Dinnerbone:
    shapes:
    - diamond_t_ns
    - diamond_t_ew

  Villain:
    shapes:
    - diamond_2pillar

